# Generated by Django 3.1.2 on 2022-03-31 15:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bpmn_id', models.CharField(max_length=99, null=True)),
                ('position', models.CharField(max_length=99, null=True)),
                ('process_bpmn_id', models.CharField(max_length=99, null=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Asset_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Asset_type',
                'verbose_name_plural': 'Assets_types',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=100)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.asset_type')),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
            },
        ),
        migrations.CreateModel(
            name='Attribute_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Attribute_value',
                'verbose_name_plural': 'Attributes_values',
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Control',
                'verbose_name_plural': 'Controls',
            },
        ),
        migrations.CreateModel(
            name='DataObjectAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(null=True)),
                ('order_of_size', models.CharField(max_length=100)),
                ('personal', models.CharField(choices=[('Yes', 'Yes'), ('Not', 'Not')], default='Yes', max_length=100)),
                ('load_dependece', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('xml', models.FileField(upload_to='processes/xml/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml', 'bpmn'])])),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=500)),
                ('multiple', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'System',
                'verbose_name_plural': 'Systems',
            },
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('owasp_ease_of_discovery', models.IntegerField(null=True)),
                ('owasp_ease_of_exploit', models.IntegerField(null=True)),
                ('owasp_intrusion_detection', models.IntegerField(null=True)),
                ('owasp_awareness', models.IntegerField(null=True)),
                ('loss_of_confidentiality', models.IntegerField(null=True)),
                ('loss_of_integrity', models.IntegerField(null=True)),
                ('loss_of_availability', models.IntegerField(null=True)),
                ('loss_of_accountability', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Threat',
                'verbose_name_plural': 'Threats',
            },
        ),
        migrations.CreateModel(
            name='ThreatAgentAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=100, null=True)),
                ('attribute_value', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatAgentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('common_actions', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatAgentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qid', models.CharField(max_length=500, null=True)),
                ('question', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatAgentRiskScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.IntegerField()),
                ('size', models.IntegerField()),
                ('motive', models.IntegerField()),
                ('opportunity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.system')),
            ],
        ),
        migrations.CreateModel(
            name='Threat_Stride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.stride')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.threat')),
            ],
        ),
        migrations.CreateModel(
            name='Threat_has_control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.control')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.threat')),
            ],
        ),
        migrations.CreateModel(
            name='Threat_has_attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.attribute')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.threat')),
            ],
        ),
        migrations.CreateModel(
            name='TAReplyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.threatagentcategory')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.reply')),
            ],
        ),
        migrations.CreateModel(
            name='TAReplies_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.threatagentquestion')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.reply')),
            ],
        ),
        migrations.CreateModel(
            name='TACategoryAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.threatagentattribute')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.threatagentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='System_ThreatAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.threatagentcategory')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.system')),
            ],
        ),
        migrations.CreateModel(
            name='StrideImpactRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financialdamage', models.IntegerField(null=True)),
                ('reputationdamage', models.IntegerField(null=True)),
                ('noncompliance', models.IntegerField(null=True)),
                ('privacyviolation', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.process')),
                ('stride', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.stride')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likelihood', models.IntegerField(null=True)),
                ('impact', models.IntegerField(null=True)),
                ('severity', models.CharField(max_length=100)),
                ('skill', models.IntegerField(null=True)),
                ('motive', models.IntegerField(null=True)),
                ('opportunity', models.IntegerField(null=True)),
                ('size', models.IntegerField(null=True)),
                ('ease_of_discovery', models.IntegerField(null=True)),
                ('ease_of_exploit', models.IntegerField(null=True)),
                ('intrusion_detection', models.IntegerField(null=True)),
                ('awareness', models.IntegerField(null=True)),
                ('loss_of_confidentiality', models.IntegerField(null=True)),
                ('loss_of_integrity', models.IntegerField(null=True)),
                ('loss_of_availability', models.IntegerField(null=True)),
                ('loss_of_accountability', models.IntegerField(null=True)),
                ('financial', models.IntegerField(null=True)),
                ('reputation', models.IntegerField(null=True)),
                ('non_compliance', models.IntegerField(null=True)),
                ('privacy', models.IntegerField(null=True)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.asset')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.process')),
                ('system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.system')),
                ('threat_stride', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.threat_stride')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.system'),
        ),
        migrations.CreateModel(
            name='OverallRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spoofing', models.CharField(max_length=100)),
                ('tampering', models.CharField(max_length=100)),
                ('repudiation', models.CharField(max_length=100)),
                ('information', models.CharField(max_length=100)),
                ('dos', models.CharField(max_length=100)),
                ('eop', models.CharField(max_length=100)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.asset')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.process')),
                ('system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.system')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.attribute_value'),
        ),
        migrations.CreateModel(
            name='Asset_has_DataObject_attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.asset')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.asset_type')),
                ('data_object_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.dataobjectattribute')),
            ],
        ),
        migrations.CreateModel(
            name='Asset_has_attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.asset')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.attribute')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.asset_type'),
        ),
        migrations.AddField(
            model_name='asset',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.process'),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('process_bpmn_id', models.IntegerField(null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.system')),
            ],
        ),
    ]
