# Generated by Django 3.1.2 on 2022-04-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='process_bpmn_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
