# Generated by Django 4.0.3 on 2022-03-07 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
            model_name='risk',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.process'),
        ),
        migrations.AddField(
            model_name='risk',
            name='severity',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threat',
            name='loss_of_accountability',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='loss_of_availability',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='loss_of_confidentiality',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='loss_of_integrity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.system'),
        ),
        migrations.AlterField(
            model_name='strideimpactrecord',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.process'),
        ),
        migrations.CreateModel(
            name='Threat_Stride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.stride')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.threat')),
            ],
        ),
        migrations.CreateModel(
            name='OverallRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spoofing', models.CharField(max_length=100)),
                ('tampering', models.CharField(max_length=100)),
                ('repudiation', models.CharField(max_length=100)),
                ('information', models.CharField(max_length=100)),
                ('dos', models.CharField(max_length=100)),
                ('eop', models.CharField(max_length=100)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.asset')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.process')),
                ('system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.system')),
            ],
        ),
        migrations.AddField(
            model_name='risk',
            name='threat_stride',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.threat_stride'),
        ),
    ]
