# Generated by Django 4.0.3 on 2022-03-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0003_dataobject_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataObject_id',
            new_name='DataObject',
        ),
    ]
