# Generated by Django 4.0.3 on 2022-04-08 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0003_auto_20220407_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataobjectattribute',
            name='personal',
            field=models.CharField(choices=[('yes', 'Yes'), ('Not', 'Not')], default='Yes', max_length=100),
        ),
        migrations.CreateModel(
            name='Task_manages_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='parsingbpmn.asset')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='parsingbpmn.asset')),
            ],
        ),
    ]
