# Generated by Django 4.0.3 on 2022-04-12 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0004_alter_dataobjectattribute_personal_task_manages_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor_manage_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.actor')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.asset')),
            ],
        ),
    ]
