# Generated by Django 4.0.3 on 2022-03-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0004_rename_dataobject_id_dataobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='threat',
        ),
    ]
