# Generated by Django 4.0.3 on 2022-04-12 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0005_actor_manage_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor_manage_data',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.process'),
        ),
    ]
