# Generated by Django 3.1.2 on 2022-03-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0007_risk_likelihood'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='process_id_bpmn',
            field=models.IntegerField(null=True),
        ),
    ]
