# Generated by Django 3.1.2 on 2022-03-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0008_process_process_id_bpmn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='process_id_bpmn',
        ),
    ]
