# Generated by Django 4.0.3 on 2022-03-31 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0009_remove_process_process_id_bpmn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('process_bpmn_id', models.IntegerField(null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.system')),
            ],
        ),
        migrations.CreateModel(
            name='Asset_has_DataObject_attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DataObjectAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(null=True)),
                ('order_of_size', models.CharField(max_length=100)),
                ('personal', models.CharField(choices=[('yes', 'Yes'), ('Not', 'Not')], default='Yes', max_length=100)),
                ('load_dependece', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='process_bpmn_id',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.DeleteModel(
            name='DataObject',
        ),
        migrations.AddField(
            model_name='asset_has_dataobject_attribute',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.asset'),
        ),
        migrations.AddField(
            model_name='asset_has_dataobject_attribute',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.asset_type'),
        ),
        migrations.AddField(
            model_name='asset_has_dataobject_attribute',
            name='data_object_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.dataobjectattribute'),
        ),
    ]
